# Generated by Django 4.0.3 on 2022-09-20 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_staff_user_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='student',
            new_name='staff',
        ),
    ]
