# Generated by Django 4.0.3 on 2022-09-20 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_student_user_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='student',
            field=models.BooleanField(default=False),
        ),
    ]
