# Generated by Django 4.0.3 on 2022-09-20 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
